# Generated by Django 5.1.6 on 2025-02-26 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo de la Tarea', max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(choices=[(1, 'Alta'), (2, 'Mediana'), (3, 'Baja')], default=3, help_text='Prioridad de la Tarea', verbose_name='Prioridad')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de Creacion de la Tarea', verbose_name='Creado en')),
                ('finish_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de Creacion de la Tarea', verbose_name='Creado en')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('tags', models.ManyToManyField(max_length=100, to='tasks.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
